run:
  tests: false
  timeout: 5m

linters:
  disable: []
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  # - contextcheck
  # - cyclop
  - decorder
  - depguard
  - dogsled
  - dupl
  - durationcheck
  - errchkjson
  - errname
  - errorlint
  - execinquery
  # - exhaustive
  # - exhaustruct
  - exportloopref
  - forbidigo
  - forcetypeassert
  # - funlen
  # - gci
  # - gochecknoglobals
  # - gochecknoinits
  # - gocognit
  - goconst
  # - gocritic
  - gocyclo
  # - godot
  # - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  # - gomnd
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - grouper
  - importas
  - interfacebloat
  # - ireturn
  # - lll
  - logrlint
  - maintidx
  - makezero
  - misspell
  - nakedret
  # - nestif
  - nilerr
  # - nilnil
  # - nlreturn
  - noctx
  - nolintlint
  # - nonamedreturns
  - nosprintfhostport
  - paralleltest
  - prealloc
  - predeclared
  - promlinter
  - reassign
  # - revive
  - rowserrcheck
  - sqlclosecheck
  - stylecheck
  # - tagliatelle
  - tenv
  - testpackage
  - thelper
  - tparallel
  - unconvert
  - unparam
  - usestdlibvars
  # - varnamelen
  - wastedassign
  - whitespace
  # - wrapcheck
  # - wsl

# golangci-lint run | grep ': ' | grep -o '([a-z]*)$' | sort > todelete.txt
# Counter(Path('todelete.txt').read_text().splitlines())
