name: Feature request / Feedback
description: Suggest an idea for this project
title: "[FEEDBACK] "
labels: [ "enhancement" ]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        Please provide as much information as possible, so we can take your feedback in account and try to improve Natun.
  - type: textarea
    id: background
    attributes:
        label: Background
        description: A clear and concise description of what the problem is
        placeholder: e.g. "I'm always frustrated when ..."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
        label: What do you propose to do?
        description: Describe the solution you'd like to see
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What have you already tried?
      description: Describe alternatives you've considered
  - type: textarea
    id: additional-info
    attributes:
      label: What else should we know?
      description: A clear use-case description can help us to understand the context, and realize if there's a problem
        here.
